# Generated by Django 4.1.7 on 2023-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
