# Generated by Django 4.1.7 on 2023-03-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_price_alter_module_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'get_latest_by': ['id'], 'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module'),
        ),
    ]
